"""
Regenerate the gRPC/protobuf stubs in ``conductor/grpc/`` from
``proto/conductor.proto``.

Usage::

    python scripts/generate_grpc.py

The generated files (``conductor_pb2.py``, ``conductor_pb2_grpc.py``) are
**committed** so users never need ``protoc`` at install time.  Each generated
file gets a header (``# mypy: ignore-errors``, ``# flake8: noqa``,
``# pyright: ignore``) and is excluded from ``black`` — see
``[tool.black] extend-exclude`` in ``pyproject.toml``.

The generated modules define their classes dynamically, so they are typed by
hand-maintained stubs ``conductor_pb2.pyi`` / ``conductor_pb2_grpc.pyi`` in the
same directory — keep those in sync when the proto changes.
"""

from __future__ import annotations

import sys
from pathlib import Path

from grpc_tools import protoc

ROOT = Path(__file__).resolve().parent.parent
PROTO_DIR = ROOT / "proto"
OUT_DIR = ROOT / "conductor" / "grpc"

HEADER = (
    "# @generated by scripts/generate_grpc.py. DO NOT EDIT.\n"
    "# flake8: noqa\n"
    "# mypy: ignore-errors\n"
    "# pyright: ignore\n"
)


def _prepend_header(path: Path) -> None:
    """Prepend the generated-file header to *path* if not already present."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("# @generated by scripts/generate_grpc.py"):
        path.write_text(HEADER + text, encoding="utf-8")


def _fix_pb2_grpc_import(path: Path) -> None:
    """Convert the flat ``import conductor_pb2`` to a package-relative import."""
    text = path.read_text(encoding="utf-8")
    text = text.replace(
        "import conductor_pb2 as conductor__pb2",
        "from . import conductor_pb2 as conductor__pb2",
    )
    path.write_text(text, encoding="utf-8")


def main() -> int:
    """Run protoc and post-process the generated stubs."""
    args = [
        "grpc_tools.protoc",
        f"-I{PROTO_DIR}",
        f"--python_out={OUT_DIR}",
        f"--grpc_python_out={OUT_DIR}",
        str(PROTO_DIR / "conductor.proto"),
    ]
    try:
        result = protoc.main(args)
    except SystemExit as exc:  # pragma: no cover - depends on protoc version
        result = int(exc.code or 1)

    if int(result) != 0:
        print("protoc failed; aborting.", file=sys.stderr)
        return int(result)

    pb2 = OUT_DIR / "conductor_pb2.py"
    pb2_grpc = OUT_DIR / "conductor_pb2_grpc.py"
    _prepend_header(pb2)
    _prepend_header(pb2_grpc)
    _fix_pb2_grpc_import(pb2_grpc)

    print(f"Generated {pb2.name}, {pb2_grpc.name} in {OUT_DIR.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
