# @generated by scripts/generate_grpc.py. DO NOT EDIT.
# flake8: noqa
# mypy: ignore-errors
# pyright: ignore
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conductor.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'conductor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63onductor.proto\x12\tconductor\"h\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x0f\n\x07persist\x18\x04 \x01(\x08\x12\x13\n\x0btraceparent\x18\x05 \x01(\t\"d\n\x0cTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0e\n\x06result\x18\x03 \x01(\x0c\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x13\n\x0btraceparent\x18\x05 \x01(\t\"$\n\x0fRegisterRequest\x12\x11\n\ttask_type\x18\x01 \x01(\t\"H\n\x10RegisterResponse\x12\x12\n\nregistered\x18\x01 \x01(\x08\x12\x11\n\ttask_type\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x0f\n\rStatusRequest\"\xca\x01\n\x0cWorkerStatus\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x16\n\x0euptime_seconds\x18\x03 \x01(\x01\x12\x1d\n\x15tasks_processed_total\x18\x04 \x01(\x03\x12\x1a\n\x12tasks_failed_total\x18\x05 \x01(\x03\x12\x1b\n\x13registered_handlers\x18\x06 \x03(\t\x12\x14\n\x0cgrpc_enabled\x18\x07 \x01(\x08\x12\x11\n\tgrpc_port\x18\x08 \x01(\x05\x32\xe3\x01\n\x0f\x43onductorWorker\x12>\n\x0bProcessTask\x12\x16.conductor.TaskRequest\x1a\x17.conductor.TaskResponse\x12J\n\x0fRegisterHandler\x12\x1a.conductor.RegisterRequest\x1a\x1b.conductor.RegisterResponse\x12\x44\n\x0fGetWorkerStatus\x12\x18.conductor.StatusRequest\x1a\x17.conductor.WorkerStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conductor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=30
  _globals['_TASKREQUEST']._serialized_end=134
  _globals['_TASKRESPONSE']._serialized_start=136
  _globals['_TASKRESPONSE']._serialized_end=236
  _globals['_REGISTERREQUEST']._serialized_start=238
  _globals['_REGISTERREQUEST']._serialized_end=274
  _globals['_REGISTERRESPONSE']._serialized_start=276
  _globals['_REGISTERRESPONSE']._serialized_end=348
  _globals['_STATUSREQUEST']._serialized_start=350
  _globals['_STATUSREQUEST']._serialized_end=365
  _globals['_WORKERSTATUS']._serialized_start=368
  _globals['_WORKERSTATUS']._serialized_end=570
  _globals['_CONDUCTORWORKER']._serialized_start=573
  _globals['_CONDUCTORWORKER']._serialized_end=800
# @@protoc_insertion_point(module_scope)
