# @generated by scripts/generate_grpc.py. DO NOT EDIT.
# flake8: noqa
# mypy: ignore-errors
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import conductor_pb2 as conductor__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in conductor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConductorWorkerStub:
    """Conductor gRPC API.

    The ConductorWorker service is served by a Conductor Worker process
    (``grpc_enabled=True``). Polyglot clients (Go, Rust, Node.js, Python)
    connect to execute tasks, register handlers, and inspect worker status.

    Payloads and results are carried as JSON-encoded ``bytes`` so clients
    can stay language-agnostic.

    The ConductorWorker service, served by a Conductor Worker.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessTask = channel.unary_unary(
                '/conductor.ConductorWorker/ProcessTask',
                request_serializer=conductor__pb2.TaskRequest.SerializeToString,
                response_deserializer=conductor__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.RegisterHandler = channel.unary_unary(
                '/conductor.ConductorWorker/RegisterHandler',
                request_serializer=conductor__pb2.RegisterRequest.SerializeToString,
                response_deserializer=conductor__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.GetWorkerStatus = channel.unary_unary(
                '/conductor.ConductorWorker/GetWorkerStatus',
                request_serializer=conductor__pb2.StatusRequest.SerializeToString,
                response_deserializer=conductor__pb2.WorkerStatus.FromString,
                _registered_method=True)


class ConductorWorkerServicer:
    """Conductor gRPC API.

    The ConductorWorker service is served by a Conductor Worker process
    (``grpc_enabled=True``). Polyglot clients (Go, Rust, Node.js, Python)
    connect to execute tasks, register handlers, and inspect worker status.

    Payloads and results are carried as JSON-encoded ``bytes`` so clients
    can stay language-agnostic.

    The ConductorWorker service, served by a Conductor Worker.
    """

    def ProcessTask(self, request, context):
        """Execute a task through the worker's registered handler and return the
        result or error. By default this is pure execution (no queue writes);
        set ``persist`` to record the outcome in ``conductor_tasks``.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterHandler(self, request, context):
        """Register (or declare) a handler for a task_type on this worker.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkerStatus(self, request, context):
        """Return worker health and statistics.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConductorWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessTask,
                    request_deserializer=conductor__pb2.TaskRequest.FromString,
                    response_serializer=conductor__pb2.TaskResponse.SerializeToString,
            ),
            'RegisterHandler': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterHandler,
                    request_deserializer=conductor__pb2.RegisterRequest.FromString,
                    response_serializer=conductor__pb2.RegisterResponse.SerializeToString,
            ),
            'GetWorkerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkerStatus,
                    request_deserializer=conductor__pb2.StatusRequest.FromString,
                    response_serializer=conductor__pb2.WorkerStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'conductor.ConductorWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('conductor.ConductorWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConductorWorker:
    """Conductor gRPC API.

    The ConductorWorker service is served by a Conductor Worker process
    (``grpc_enabled=True``). Polyglot clients (Go, Rust, Node.js, Python)
    connect to execute tasks, register handlers, and inspect worker status.

    Payloads and results are carried as JSON-encoded ``bytes`` so clients
    can stay language-agnostic.

    The ConductorWorker service, served by a Conductor Worker.
    """

    @staticmethod
    def ProcessTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conductor.ConductorWorker/ProcessTask',
            conductor__pb2.TaskRequest.SerializeToString,
            conductor__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterHandler(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conductor.ConductorWorker/RegisterHandler',
            conductor__pb2.RegisterRequest.SerializeToString,
            conductor__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/conductor.ConductorWorker/GetWorkerStatus',
            conductor__pb2.StatusRequest.SerializeToString,
            conductor__pb2.WorkerStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
